from django.urls import path
from app.views import (ProductView,
                       ProductsList,
                       main,
                       cart_view,
                       empty_section,
                       login,
                       phone,
                       smartphones,
                       Categories,
                       products_of_category,
                       product_detail,
                       add_to_cart_view,
                       remove_from_cart_view,
                       change_item_quantity_view,
                       checkout_view,
                       order_create_view,
                       congratulations_view)

urlpatterns = [
    path('', main, name='main_page'),
    path('category/<str:slug>/', products_of_category, name='category'),
    path('product/<str:slug>/', product_detail, name='product'),
    path('add_to_cart/', add_to_cart_view, name='add_to_cart'),
    path('remove_from_cart/', remove_from_cart_view, name='remove_from_cart'),
    path('change_item_quantity/', change_item_quantity_view, name='change_item_quantity'),
    path('cart/', cart_view, name='cart'),
    path('cart/checkout/', checkout_view, name='checkout'),
    path('empty_section/', empty_section, name='empty_section'),
    path('smartphones/', smartphones, name='smartphones'),
    path('cart/order/', order_create_view, name='order_create'),
    path('cart/congratulations/', congratulations_view, name='congratulations'),
]
# ProductView.as_view()
# path('dada/<str:category>/<int:id>', Categories.as_view()),
# path('category/<str:category>/<int:id>', phone, name='product'),
# path('phone/<int:id>/', phone, name='phone'),